AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudWatch Logs Lifecycle Policy for cost optimization
  Automatically manages log retention and archival for 7H Stock Analyzer

Resources:
  # Lambda Function Logs Lifecycle Policy
  LambdaLogsLifecyclePolicy:
    Type: AWS::Logs::LifecyclePolicy
    Properties:
      PolicyName: "7H-Stock-Analyzer-Lambda-Logs-Policy"
      PolicyDocument:
        {
          "filters": [
            {
              "logGroupNamePrefix": "/aws/lambda/7h-stock-analyzer"
            }
          ],
          "selection": "LogGroupNamePrefix",
          "retention": {
            "days": 3,
            "storageClass": "STANDARD"
          },
          "transition": {
            "days": 1,
            "storageClass": "IA"  # Move to Infrequent Access after 1 day
          }
        }
      Description: "Cost-optimized lifecycle policy for Lambda logs"

  # API Gateway Logs Lifecycle Policy  
  ApiGatewayLogsLifecyclePolicy:
    Type: AWS::Logs::LifecyclePolicy
    Properties:
      PolicyName: "7H-Stock-Analyzer-API-Gateway-Logs-Policy"
      PolicyDocument:
        {
          "filters": [
            {
              "logGroupNamePrefix": "API-Gateway-Execution-Logs"
            }
          ],
          "selection": "LogGroupNamePrefix",
          "retention": {
            "days": 7,
            "storageClass": "STANDARD"
          },
          "transition": {
            "days": 2,
            "storageClass": "IA"
          }
        }
      Description: "Lifecycle policy for API Gateway logs"

  # Custom Application Logs Lifecycle Policy
  ApplicationLogsLifecyclePolicy:
    Type: AWS::Logs::LifecyclePolicy
    Properties:
      PolicyName: "7H-Stock-Analyzer-Application-Logs-Policy"
      PolicyDocument:
        {
          "filters": [
            {
              "logGroupNamePrefix": "/aws/lambda/stock-analyzer"
            }
          ],
          "selection": "LogGroupNamePrefix",
          "retention": {
            "days": 1,
            "storageClass": "STANDARD"
          }
        }
      Description: "Aggressive retention for application logs"

  # Metric Filter for Error Monitoring (Cost-effective)
  ErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StockAnalyzerFunction}"
      FilterPattern: '[ERROR, CRITICAL]'
      MetricTransformations:
        - MetricName: "ErrorCount"
          MetricNamespace: "7H-Stock-Analyzer"
          MetricValue: "1"

  # Metric Filter for Performance Monitoring
  PerformanceMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StockAnalyzerFunction}"
      FilterPattern: '[ANALYSIS]'
      MetricTransformations:
        - MetricName: "AnalysisCount"
          MetricNamespace: "7H-Stock-Analyzer"
          MetricValue: "1"

Parameters:
  StockAnalyzerFunction:
    Type: String
    Description: Name of the Lambda function
    Default: "7h-stock-analyzer-StockAnalyzerFunction"

Outputs:
  LambdaLogsLifecyclePolicyArn:
    Description: "ARN of the Lambda logs lifecycle policy"
    Value: !GetAtt LambdaLogsLifecyclePolicy.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaLogsLifecyclePolicy"

  ApiGatewayLogsLifecyclePolicyArn:
    Description: "ARN of the API Gateway logs lifecycle policy"
    Value: !GetAtt ApiGatewayLogsLifecyclePolicy.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayLogsLifecyclePolicy"
