AWSTemplateFormatVersion: '2010-09-09'
Description: 7H Stock Analyzer - Infrastructure (S3, CloudFront, API Gateway)

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - dev

Resources:
  StockDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: 7h-stock-analyzer
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
            BucketKeyEnabled: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldDailyFiles
            Status: Enabled
            ExpirationInDays: 365
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 30
          - Id: DeleteTempFiles
            Status: Enabled
            ExpirationInDays: 7
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "Content-Type"
              - "Authorization"
              - "X-API-Key"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "http://7h-stock-analyzer.s3-website-us-east-1.amazonaws.com"
              - "https://7h-stock-analyzer.s3-website-us-east-1.amazonaws.com"
            MaxAgeSeconds: 3600

  StockDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StockDataBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action:
              - "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${StockDataBucket}/*"
          - Sid: "AllowPublicReadAccessToDataFiles"
            Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}/data/*"
              - !Sub "arn:aws:s3:::${StockDataBucket}/recon/*"
              - !Sub "arn:aws:s3:::${StockDataBucket}/config/*"
          - Sid: "AllowHTTPSOnly"
            Effect: "Deny"
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}"
              - !Sub "arn:aws:s3:::${StockDataBucket}/*"
            Condition:
              Bool:
                "aws:SecureTransport": false

  StockAnalyzerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: API Gateway with security and cost controls - Write operations only
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Key"
        AllowOrigins:
          - "https://d37m5zz5fkglhg.cloudfront.net"
          - "http://7h-stock-analyzer.s3-website-us-east-1.amazonaws.com"
          - "https://7h-stock-analyzer.s3-website-us-east-1.amazonaws.com"
          - "http://localhost:3000"
          - "http://localhost:8080"
        MaxAge: 3600
      RouteSettings:
        "POST /run-now":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "POST /recon/run":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "POST /config/update":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "POST /config/validate":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "POST /analysis/{symbol}":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /recommendations":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /health":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /analysis/{ticker}":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /analysis/{ticker}/signals":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /analysis/{ticker}/indicators":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /config/{config_type}":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /config/{config_type}.json":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /history/dates":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /history/{date}":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
      DefaultRouteSettings:
        ThrottlingBurstLimit: 3
        ThrottlingRateLimit: 1

  StockAnalyzerCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CallerReference: !Sub "${AWS::StackName}-frontend-${AWS::AccountId}"
        Comment: !Sub "${AWS::StackName} frontend"
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !Sub "${StockDataBucket}.s3-website-${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginSslProtocols:
                - TLSv1.2
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        Enabled: true
        PriceClass: PriceClass_100

Outputs:
  StockDataBucket:
    Description: "S3 bucket for stock data"
    Value: !Ref StockDataBucket
    Export:
      Name: "7h-Stock-DataBucket"

  StockAnalyzerApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${StockAnalyzerApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-StockAnalyzerApi"

  StockAnalyzerCloudFront:
    Description: "CloudFront distribution URL"
    Value: !Sub "https://${StockAnalyzerCloudFront.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-StockAnalyzerCloudFront"
