AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 7H Stock Analyzer - Serverless Stock Analysis Application

Globals:
  Function:
    Runtime: python3.10
    Timeout: 900
    MemorySize: 512
    Environment:
      Variables:
        APP_AWS_REGION: !Ref AWS::Region
        S3_BUCKET_NAME: !Ref StockDataBucket
        LOG_LEVEL: INFO
        ENVIRONMENT: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - dev

Resources:
  StockAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      CodeUri: s3://7h-stock-analyzer/stock-analyzer-lambda.zip
      Description: Lambda function for stock analysis with FastAPI
      Architectures:
        - x86_64
      Layers:
        - !Ref DependenciesLayer
      Runtime: python3.10
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          APP_AWS_REGION: !Ref AWS::Region
          S3_BUCKET_NAME: !Ref StockDataBucket
          LOG_LEVEL: INFO
          ENVIRONMENT: !Ref Environment
      Role: !GetAtt StockAnalyzerExecutionRole.Arn
      Events:
        ApiHealth:
          Type: HttpApi
          Properties:
            Path: /health
            Method: GET
        ApiRunNow:
          Type: HttpApi
          Properties:
            Path: /run-now
            Method: POST
        ApiReconRun:
          Type: HttpApi
          Properties:
            Path: /recon/run
            Method: POST
        ApiConfigUpdate:
          Type: HttpApi
          Properties:
            Path: /config/update
            Method: POST
        ApiConfigValidate:
          Type: HttpApi
          Properties:
            Path: /config/validate
            Method: POST
        ApiAnalysis:
          Type: HttpApi
          Properties:
            Path: /analysis/{symbol}
            Method: POST
        ApiRecommendationsFallback:
          Type: HttpApi
          Properties:
            Path: /recommendations
            Method: GET

  StockAnalyzerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${StockDataBucket}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub "arn:aws:s3:::${StockDataBucket}/*"

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: StockAnalyzerDependencies
      Description: Shared dependencies for stock analyzer
      ContentUri: s3://7h-stock-analyzer/stock-analyzer-layer.zip
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain

  StockDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
            BucketKeyEnabled: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldDailyFiles
            Status: Enabled
            ExpirationInDays: 365
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 30
          - Id: DeleteTempFiles
            Status: Enabled
            ExpirationInDays: 7
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "Content-Type"
              - "Authorization"
              - "X-API-Key"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "http://7h-stock-analyzer.s3-website-us-east-1.amazonaws.com"
              - "https://7h-stock-analyzer.s3-website-us-east-1.amazonaws.com"
            MaxAgeSeconds: 3600

  StockDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StockDataBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action:
              - "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${StockDataBucket}/*"
          - Sid: "AllowPublicReadAccessToDataFiles"
            Effect: "Allow"
            Principal: "*"
            Action: "s3:GetObject"
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}/data/*"
              - !Sub "arn:aws:s3:::${StockDataBucket}/recon/*"
              - !Sub "arn:aws:s3:::${StockDataBucket}/config/*"
          - Sid: "AllowHTTPSOnly"
            Effect: "Deny"
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}"
              - !Sub "arn:aws:s3:::${StockDataBucket}/*"
            Condition:
              Bool:
                "aws:SecureTransport": false

  StockAnalyzerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: API Gateway with security and cost controls - Write operations only
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Key"
        AllowOrigins:
          - "https://d37m5zz5fkglhg.cloudfront.net"
          - "http://7h-stock-analyzer.s3-website-us-east-1.amazonaws.com"
          - "https://7h-stock-analyzer.s3-website-us-east-1.amazonaws.com"
          - "http://localhost:3000"
          - "http://localhost:8080"
        MaxAge: 3600
      RouteSettings:
        "POST /run-now":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "POST /recon/run":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "POST /config/update":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "POST /config/validate":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "POST /analysis/{symbol}":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /recommendations":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /health":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /analysis/{ticker}":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /analysis/{ticker}/signals":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
        "GET /analysis/{ticker}/indicators":
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 1
      DefaultRouteSettings:
        ThrottlingBurstLimit: 3
        ThrottlingRateLimit: 1

  StockAnalyzerCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CallerReference: !Sub "${AWS::StackName}-frontend-${AWS::AccountId}"
        Comment: !Sub "${AWS::StackName} frontend"
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !Sub "${StockDataBucket}.s3-website-${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginSslProtocols:
                - TLSv1.2
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
        Enabled: true
        PriceClass: PriceClass_100

  StockAnalyzerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StockAnalyzerFunction}"
      RetentionInDays: 3

Outputs:
  StockAnalyzerFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt StockAnalyzerFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-StockAnalyzerFunction"

  StockAnalyzerApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${StockAnalyzerApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-StockAnalyzerApi"

  StockDataBucket:
    Description: "S3 bucket for stock data"
    Value: !Ref StockDataBucket
    Export:
      Name: !Sub "${AWS::StackName}-StockDataBucket"

  StockAnalyzerCloudFront:
    Description: "CloudFront distribution URL"
    Value: !Sub "https://${StockAnalyzerCloudFront.DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-StockAnalyzerCloudFront"
