AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Features: Target prices, stop losses, confidence levels, recon, purge, security

Globals:
  Function:
    Runtime: python3.10
    Timeout: 900
    MemorySize: 512
    Environment:
      Variables:
        AWS_REGION: !Ref AWS::Region
        S3_BUCKET_NAME: !Ref StockDataBucket
        PUSHOVER_TOKEN: !Ref PushoverToken
        PUSHOVER_USER: !Ref PushoverUser
        ENABLE_NOTIFICATIONS: "true"
        LOG_LEVEL: "WARNING"
        ENVIRONMENT: "prod"
        ENABLE_VERBOSE_LOGGING: "false"
        ENABLE_STRUCTURED_LOGGING: "true"
        REQUIRE_AUTH: "true"
        API_KEY: "{{resolve:ssm:/stock-analyzer/api-key:1}}"
    Tags:
      Project: "7H-Stock-Analyzer"
      Environment: "Production"

Parameters:
  PushoverToken:
    Type: String
    Description: Pushover API token for notifications
    Default: ""
    NoEcho: true
  PushoverUser:
    Type: String
    Description: Pushover user key for notifications
    Default: ""
    NoEcho: true
  Environment:
    Type: String
    Description: Environment name (dev/staging/prod)
    Default: "dev"
    AllowedValues: ["dev", "staging", "prod"]
  EnableVpc:
    Type: String
    Description: Enable VPC isolation for enhanced security
    Default: "false"
    AllowedValues: ["true", "false"]

Resources:
  StockAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      CodeUri: s3://7h-stock-analyzer/stock-analyzer-lambda.zip
      Description: Lambda function for stock analysis with FastAPI
      Architectures:
        - x86_64
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !Sub "arn:aws:s3:::${StockDataBucket}"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource: !Sub "arn:aws:s3:::${StockDataBucket}/*"
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${StockAnalyzerFunction}*"
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        CronTrigger30Min:
          Type: Schedule
          Properties:
            Schedule: cron(0 15 ? * MON-FRI *)
            Name: StockAnalyzerCron30Min
            Description: Trigger stock analysis 30 minutes after market open
            Enabled: true
            RetryPolicy:
              MaximumRetryAttempts: 1
              MaximumEventAgeInSeconds: 1800
        CronTriggerMidday:
          Type: Schedule
          Properties:
            Schedule: cron(30 17 ? * MON-FRI *)
            Name: StockAnalyzerCronMidday
            Description: Trigger stock analysis at midday trading
            Enabled: true
            RetryPolicy:
              MaximumRetryAttempts: 1
              MaximumEventAgeInSeconds: 1800
        CronTriggerWeeklyRecon:
          Type: Schedule
          Properties:
            Schedule: cron(0 23 ? * SUN *)
            Name: StockAnalyzerWeeklyRecon
            Description: Trigger weekly reconciliation for performance tracking
            Enabled: true
            RetryPolicy:
              MaximumRetryAttempts: 2
              MaximumEventAgeInSeconds: 3600

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: StockAnalyzerDependencies
      Description: Shared dependencies for stock analyzer
      ContentUri: s3://7h-stock-analyzer/stock-analyzer-layer.zip
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain

  StockDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "7h-stock-analyzer-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
        MfaDelete: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
            BucketKeyEnabled: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldDailyFiles
            Status: Enabled
            ExpirationInDays: 365
            Filter:
              Prefix: data/daily/
          - Id: DeleteOldReconFiles
            Status: Enabled
            ExpirationInDays: 180
            Filter:
              Prefix: recon/daily/
          - Id: DeleteOldCharts
            Status: Enabled
            ExpirationInDays: 30
            Filter:
              Prefix: charts/
          - Id: DeleteTempFiles
            Status: Enabled
            ExpirationInDays: 7
            Filter:
              Prefix: temp/
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 30
            Filter:
              Prefix: logs/
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["Content-Type", "Authorization"]
            AllowedMethods: [GET, HEAD, OPTIONS]
            AllowedOrigins: ["https://*.amazonaws.com", "http://localhost:*"]
            MaxAge: 3600
            ExposedHeaders: []

  StockDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StockDataBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadWebsiteFiles
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}/index.html"
              - !Sub "arn:aws:s3:::${StockDataBucket}/error.html"
              - !Sub "arn:aws:s3:::${StockDataBucket}/public/*"
              - !Sub "arn:aws:s3:::${StockDataBucket}/assets/*"
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}"
              - !Sub "arn:aws:s3:::${StockDataBucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: LambdaAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt StockAnalyzerFunction.Arn
            Action: 
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}"
              - !Sub "arn:aws:s3:::${StockDataBucket}/*"
          - Sid: RootAccountAccess
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: 
              - s3:*
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}"
              - !Sub "arn:aws:s3:::${StockDataBucket}/*"
          - Sid: CurrentUserAccess
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action: 
              - s3:*
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}"
              - !Sub "arn:aws:s3:::${StockDataBucket}/*"
          - Sid: DenyAllOtherAccess
            Effect: Deny
            NotPrincipal:
              AWS:
                - !GetAtt StockAnalyzerFunction.Arn
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
                - !Ref AWS::AccountId
            Action: s3:*
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}"
              - !Sub "arn:aws:s3:::${StockDataBucket}/*"

  StockAnalyzerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: API Gateway with security and cost controls
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - "Content-Type"
          - "X-API-Key"
        AllowOrigins:
          - "https://*.amazonaws.com"
          - "http://localhost:*"
        MaxAge: 3600

  StockAnalyzerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StockAnalyzerFunction}"
      RetentionInDays: 3


  Conditions:
  EnableVpcCondition: !Equals [!Ref EnableVpc, "true"]

Outputs:
  StockAnalyzerFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt StockAnalyzerFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-StockAnalyzerFunction"

  StockAnalyzerApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${StockAnalyzerApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: !Sub "${AWS::StackName}-StockAnalyzerApi"

  StockDataBucket:
    Description: "S3 bucket for stock data"
    Value: !Ref StockDataBucket
    Export:
      Name: !Sub "${AWS::StackName}-StockDataBucket"

  StockDataBucketURL:
    Description: "S3 bucket website URL"
    Value: !Sub "http://${StockDataBucket}.s3-website-${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-StockDataBucketURL"
