AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 7H Stock Analyzer - Serverless Stock Analysis Application

Globals:
  Function:
    Runtime: python3.10
    Timeout: 900
    MemorySize: 512
    Environment:
      Variables:
        APP_AWS_REGION: !Ref AWS::Region
        S3_BUCKET_NAME: !Ref StockDataBucket
        LOG_LEVEL: INFO
        ENVIRONMENT: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - dev

Resources:
  StockAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      CodeUri: s3://7h-stock-analyzer/stock-analyzer-lambda.zip
      Description: Lambda function for stock analysis with FastAPI
      Architectures:
        - x86_64
      Layers:
        - !Ref DependenciesLayer
      Runtime: python3.10
      Timeout: 900
      MemorySize: 512
      Environment:
        Variables:
          APP_AWS_REGION: !Ref AWS::Region
          S3_BUCKET_NAME: !Ref StockDataBucket
          LOG_LEVEL: INFO
          ENVIRONMENT: !Ref Environment
      Role: !GetAtt StockAnalyzerExecutionRole.Arn
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

  StockAnalyzerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-execution-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Sub "arn:aws:s3:::${StockDataBucket}"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub "arn:aws:s3:::${StockDataBucket}/*"

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: StockAnalyzerDependencies
      Description: Shared dependencies for stock analyzer
      ContentUri: s3://7h-stock-analyzer/stock-analyzer-layer.zip
      CompatibleRuntimes:
        - python3.10
      RetentionPolicy: Retain

  StockDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "7h-stock-analyzer-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3
            BucketKeyEnabled: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldDailyFiles
            Status: Enabled
            ExpirationInDays: 365
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 30
          - Id: DeleteTempFiles
            Status: Enabled
            ExpirationInDays: 7

  StockDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StockDataBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudFrontServicePrincipal"
            Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action:
              - "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${StockDataBucket}/*"
          - Sid: "AllowHTTPSOnly"
            Effect: "Deny"
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !Sub "arn:aws:s3:::${StockDataBucket}"
              - !Sub "arn:aws:s3:::${StockDataBucket}/*"
            Condition:
              Bool:
                "aws:SecureTransport": false

  StockAnalyzerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: API Gateway with security and cost controls
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-API-Key"
        AllowOrigins:
          - "https://d224ztwcw6zi6e.cloudfront.net"
          - "http://localhost:3000"
          - "http://localhost:8080"
        MaxAge: 3600

  StockAnalyzerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StockAnalyzerFunction}"
      RetentionInDays: 3

Outputs:
  StockAnalyzerFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt StockAnalyzerFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-StockAnalyzerFunction"

  StockAnalyzerApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${StockAnalyzerApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-StockAnalyzerApi"

  StockDataBucket:
    Description: "S3 bucket for stock data"
    Value: !Ref StockDataBucket
    Export:
      Name: !Sub "${AWS::StackName}-StockDataBucket"
